Bank/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('UserAccount.urls')),
]

UserAccount/urls.py
from django.urls import path
from .views import FetchUserData, ViewUserData

urlpatterns = [
    path('fetch_data/', FetchUserData.as_view(),  name='fetch-data'),
    path('view_data/', ViewUserData.as_view(), name='view-data'),
]

UserAccount/models.py
from django.db import models

class User(models.Model):
	name = models.CharField(max_length=50)
	email = models.EmailField(max_length = 50)
	mobile = models.CharField(max_length = 10)
	pan = models.CharField(max_length=10, unique=True)
	total_number_of_accounts = models.IntegerField()
	credit_score = models.IntegerField()
	address = models.CharField(max_length=100)
	def __str__(self):
		return self.email
		
class Account(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	account_no = models.CharField(max_length=50)
	amount_overdue = models.FloatField()
	current_balance = models.FloatField()
	date_opened = models.DateField()
	date_reported = models.DateField()
	lender = models.CharField(max_length=50)
	sanction_amount = models.FloatField()
	type = models.CharField(max_length=50)
	def __str__(self):
		return self.account_no

UserAccount/views.py
from django.shortcuts import render
import requests
import datetime
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from .models import User, Account
from .serializers import *

class FetchUserData(APIView):

	def get(self, request):
		
		try:
			data = requests.get('https://arkneofinance.com/api/sample_credit_report')
			user_info = data.json()
			user_info = user_info['data']
			account_infos = user_info['accounts']

			for account_info in account_infos:
				account_info['date_opened'] = datetime.datetime.strptime(
																	account_info['date_opened'], "%d-%m-%Y"
																	).strftime("%Y-%m-%d")
				account_info['date_reported'] = datetime.datetime.strptime(
																	account_info['date_reported'], "%d-%m-%Y"
																	).strftime("%Y-%m-%d")	
		
		except Exception as e:
			return Response(
					{
						"Message":e
					},
					status = status.HTTP_400_BAD_REQUEST
			)
		
		serializer = UserSerializer(data=user_info)
		
		if serializer.is_valid(raise_exception=ValueError):
			serializer.create(validated_data=user_info)
			return Response(
					{
						"Message":"User details saved successfully!!"
					},
					status = status.HTTP_201_CREATED
			)
		return Response(
						serializer.error_messages,
                        status=status.HTTP_400_BAD_REQUEST
                    )


class ViewUserData(APIView):

	def get(self, request):
		user = User.objects.all()
		return render(
						request, 
						'UserAccount/user_info.html', 
						{'user':user}
					)

templates/UserAccount/user_info.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
		<title>
			User Details
		</title>
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" href="{% static 'css/user_info.css' %}">
	</head>
<body>
	{% for usr in user %}
		<div class="about">
			<h1 class="text-center">
				User Details
			</h1>
	   		<div class="col-lg-8 col-md-8 col-sm-12 desc">
	   			<h4>
	   				Name : {{ usr.name }}
	   			</h4>
			    <p>
			    	Email : {{ usr.email }}
			    </p>
			    <p>
			    	Mobile No. : {{ usr.mobile }}
			    </p>
			    <p>
			    	Pan No. : {{usr.pan}}
			    </p>
			    <p>
			    	Address : {{ usr.address }}
			    </p>
			    <h6>
			    	Total No. of account : {{ usr.total_number_of_accounts }}
			    </h6>
			    <h6>
			    	Credit Score : {{ usr.credit_score }}
			    </h6>
		   </div>
	  	</div>
	  	<div class="blog">
			<div class="container">
			 	<h1 class="text-center">
			 		Account Details
			 	</h1>
			 	{% for account in usr.account_set.all %}
					<div class="card">
					 	<div class="card-img">
					    	<h4 >
					    		Account No. : {{ account.account_no }}
					    	</h4>
					    	<h6>  
					    		(Type : {{ account.type }}) 
					    	</h6>
					    </div>
					    <div class="card-body">
					    	<h4 class="card-title">
					    		Lender : {{ account.lender }}
					    	</h4>
						    <p class="card-text">
								<p>
									Current Balance : {{ account.current_balance }}
								</p>
								<p>
									Amount Overdue : {{ account.amount_overdue }}
								</p>
								<p>
									Sanction Amount : {{ account.sanction_amount }}
								</p>
					      	</p>
					    </div>
					    <div class="card-footer">
					      	<h6> 
					      		Date Opened : {{ account.date_opened }} 
					      	</h6>
							<h6> 
								Date Reported: {{ account.date_reported }} 
							</h6>
					    </div>
					</div>
				{% endfor %}
			</div>
		</div>
	{% endfor %}
	<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
</body>
</html>